import { IOrder } from '../interfaces/interfaceOrder';

// export const products: IProduct[] = [
//     {
//         sku: 'SKU123',
//         name: 'T-Shirt',
//         description: 'Cotton T-Shirt with a cool design',
//         pricing: {
//             price: 15.99,
//             promotionPrice: 12.99,
//             discountPercentage: 20,
//         },
//         stock: 50,
//         category: { _id: 'cat01', name: 'Clothing' },
//         brand: { _id: 'brand01', name: 'BrandX' },
//         supplier: { _id: 'sup01', name: 'Supplier A' },
//         sizes: ['S', 'M', 'L', 'XL'],
//         colors: ['Red', 'Blue', 'Green'],
//         images: ['', 'image2.jpg'],
//         ratings: 4.5,
//         gender: ['Unisex'],
//         status: 'active',
//         availability: 'in-stock',
//     },
//     {
//         sku: 'SKU124',
//         name: 'Jeans',
//         description: 'Denim jeans with a modern fit',
//         pricing: {
//             price: 39.99,
//             promotionPrice: 35.99,
//             discountPercentage: 10,
//         },
//         stock: 100,
//         category: { _id: 'cat02', name: 'Clothing' },
//         brand: { _id: 'brand02', name: 'BrandY' },
//         supplier: { _id: 'sup02', name: 'Supplier B' },
//         sizes: ['32', '34', '36'],
//         colors: ['Black', 'Indigo'],
//         images: ['', 'image4.jpg'],
//         ratings: 4.7,
//         status: 'active',
//         availability: 'in-stock',
//     },
//     {
//         sku: 'SKU125',
//         name: 'Sneakers',
//         description: 'Comfortable running shoes for all-day wear',
//         pricing: {
//             price: 59.99,
//             promotionPrice: 0,
//             discountPercentage: 0,
//         },
//         stock: 30,
//         category: { _id: 'cat03', name: 'Footwear' },
//         brand: { _id: 'brand03', name: 'BrandZ' },
//         supplier: { _id: 'sup03', name: 'Supplier C' },
//         sizes: ['7', '8', '9', '10'],
//         colors: ['White', 'Grey'],
//         images: ['', 'image6.jpg'],
//         ratings: 4.8,
//         status: 'active',
//         availability: 'in-stock',
//     },
//     {
//         sku: 'SKU126',
//         name: "Men's Jacket",
//         description: 'Stylish winter jacket with warm lining',
//         pricing: {
//             price: 79.99,
//             promotionPrice: 69.99,
//             discountPercentage: 12,
//         },
//         stock: 20,
//         category: { _id: 'cat04', name: 'Outerwear' },
//         brand: { _id: 'brand04', name: 'BrandA' },
//         supplier: { _id: 'sup04', name: 'Supplier D' },
//         sizes: ['M', 'L', 'XL'],
//         colors: ['Black', 'Navy'],
//         images: ['', 'image8.jpg'],
//         ratings: 4.6,
//         gender: ['Men'],
//         status: 'active',
//         availability: 'in-stock',
//     },
//     {
//         sku: 'SKU127',
//         name: 'Wireless Headphones',
//         description: 'Noise-cancelling headphones with Bluetooth connectivity',
//         pricing: {
//             price: 129.99,
//             promotionPrice: 109.99,
//             discountPercentage: 15,
//         },
//         stock: 0,
//         category: { _id: 'cat05', name: 'Electronics' },
//         brand: { _id: 'brand05', name: 'BrandB' },
//         supplier: { _id: 'sup05', name: 'Supplier E' },
//         sizes: [],
//         colors: ['Black', 'Silver'],
//         images: ['', 'image10.jpg'],
//         ratings: 4.9,
//         status: 'active',
//         availability: 'out-of-stock',
//     },
//     // {
//     //     sku: 'SKU128',
//     //     name: 'Yoga Mat',
//     //     description: 'Non-slip yoga mat for all exercise types, 6mm thick',
//     //     pricing: {
//     //         price: 25.99,
//     //         promotionPrice: 19.99,
//     //         discountPercentage: 15,
//     //     },
//     //     stock: 80,
//     //     category: { _id: 'cat06', name: 'Fitness' },
//     //     brand: { _id: 'brand06', name: 'BrandC' },
//     //     supplier: { _id: 'sup06', name: 'Supplier F' },
//     //     sizes: ['183x61cm'],
//     //     colors: ['Purple', 'Blue'],
//     //     images: ['image11.jpg', 'image12.jpg'],
//     //     ratings: 4.7,
//     //     status: 'active',
//     //     availability: 'in-stock',
//     // },
//     // {
//     //     sku: 'SKU129',
//     //     name: 'Phone Case',
//     //     description: 'Durable phone case for iPhone 13, shockproof design',
//     //     pricing: {
//     //         price: 14.99,
//     //         promotionPrice: 12.99,
//     //         discountPercentage: 13,
//     //     },
//     //     stock: 150,
//     //     category: { _id: 'cat07', name: 'Accessories' },
//     //     brand: { _id: 'brand07', name: 'BrandD' },
//     //     supplier: { _id: 'sup07', name: 'Supplier G' },
//     //     sizes: [],
//     //     colors: ['Black', 'Red', 'Blue'],
//     //     images: [],
//     //     ratings: 4.3,
//     //     status: 'active',
//     //     availability: 'in-stock',
//     // },
//     // {
//     //     sku: 'SKU130',
//     //     name: 'Sunglasses',
//     //     description: 'Stylish sunglasses for sunny days',
//     //     pricing: {
//     //         price: 99.99,
//     //         promotionPrice: 89.99,
//     //         discountPercentage: 10,
//     //     },
//     //     stock: 15,
//     //     category: { _id: 'cat08', name: 'Accessories' },
//     //     brand: { _id: 'brand08', name: 'BrandE' },
//     //     supplier: { _id: 'sup08', name: 'Supplier H' },
//     //     sizes: [],
//     //     colors: ['Black', 'Brown'],
//     //     images: ['image13.jpg', 'image14.jpg'],
//     //     ratings: 4.2,
//     //     status: 'active',
//     //     availability: 'in-stock',
//     // },
//     // {
//     //     sku: 'SKU131',
//     //     name: 'Laptop Sleeve',
//     //     description: 'Protective sleeve for laptops up to 15 inches',
//     //     pricing: {
//     //         price: 0,
//     //         promotionPrice: 0,
//     //         discountPercentage: 0,
//     //     },
//     //     stock: 120,
//     //     category: { _id: 'cat09', name: 'Electronics' },
//     //     brand: { _id: 'brand09', name: 'BrandF' },
//     //     supplier: { _id: 'sup09', name: 'Supplier I' },
//     //     sizes: ['15-inch'],
//     //     colors: ['Gray', 'Black'],
//     //     images: ['image15.jpg', 'image16.jpg'],
//     //     ratings: 4.4,
//     //     status: 'active',
//     //     availability: 'in-stock',
//     // },
//     // {
//     //     sku: 'SKU132',
//     //     name: 'Blender',
//     //     description: 'High-speed blender with multiple blending settings',
//     //     pricing: {
//     //         price: 99.99,
//     //         promotionPrice: 89.99,
//     //         discountPercentage: 10,
//     //     },
//     //     stock: 15,
//     //     category: {},
//     //     brand: { _id: 'brand10', name: 'BrandG' },
//     //     supplier: { _id: 'sup10', name: 'Supplier J' },
//     //     sizes: [],
//     //     colors: ['Black'],
//     //     images: ['image17.jpg', 'image18.jpg'],
//     //     ratings: 4.6,
//     //     status: 'active',
//     //     availability: 'in-stock',
//     // },
// ];

export const subBanners = [
    {
        image: 'https://example.com/images/banner1.jpg',
        title: 'New Winter Collection',
        name: 'Cozy Knit Sweater',
        price: 49.99,
        discountPrice: 39.99,
    },
    {
        image: 'https://example.com/images/banner2.jpg',
        title: 'Elegant Evening Wear',
        name: 'Velvet Maxi Dress',
        price: 89.99,
        discountPrice: 74.99,
    },
    {
        image: 'https://example.com/images/banner3.jpg',
        title: 'Everyday Essentials',
        name: 'Classic Denim Jacket',
        price: 59.99,
        discountPrice: 49.99,
    },
    {
        image: 'https://example.com/images/banner4.jpg',
        title: 'Athleisure Styles',
        name: 'Sporty Tracksuit Set',
        price: 69.99,
        discountPrice: 59.99,
    },
    {
        image: 'https://example.com/images/banner5.jpg',
        title: 'Luxury Accessories',
        name: 'Leather Crossbody Bag',
        price: 129.99,
        discountPrice: 109.99,
    },
    {
        image: 'https://example.com/images/banner2.jpg',
        title: 'Elegant Evening Wear',
        name: 'Velvet Maxi Dress',
        price: 89.99,
        discountPrice: 74.99,
    },
    {
        image: 'https://example.com/images/banner3.jpg',
        title: 'Everyday Essentials',
        name: 'Classic Denim Jacket',
        price: 59.99,
        discountPrice: 49.99,
    },
    {
        image: 'https://example.com/images/banner4.jpg',
        title: 'Athleisure Styles',
        name: 'Sporty Tracksuit Set',
        price: 69.99,
        discountPrice: 59.99,
    },
];

export const orders: IOrder[] = [
    {
        _id: '63e4b1c9f5a10a0012aabc01',
        _idProduct: '63e4a1c9f5a10a0012aabc01',
        productImage: 'https://example.com/images/banner1.jpg',
        productName: 'Áo Thun Nam',
        productColor: 'Blue',
        productSize: 'M',
        sellingPrice: 200000,
        quantity: 2,
    },
    {
        _id: '63e4b1c9f5a10a0012aabc02',
        _idProduct: '63e4a1c9f5a10a0012aabc02',
        productImage:
            'https://images.unsplash.com/photo-1544957992-20514f595d6f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGZhc2hpb258ZW58MHx8MHx8fDA%3D',
        productName: 'Quần Jeans Nữ',
        productColor: 'Black',
        productSize: 'L',
        sellingPrice: 350000,
        quantity: 1,
    },
    {
        _id: '63e4b1c9f5a10a0012aabc03',
        _idProduct: '63e4a1c9f5a10a0012aabc03',
        productImage: 'https://example.com/product3.jpg',
        productName: 'Giày Thể Thao',
        productColor: 'White',
        productSize: '42',
        sellingPrice: 500000,
        quantity: 3,
    },
    {
        _id: '63e4b1c9f5a10a0012aabc04',
        _idProduct: '63e4a1c9f5a10a0012aabc04',
        productImage: 'https://example.com/product4.jpg',
        productName: 'Túi Xách Tay',
        productColor: 'Pink',
        productSize: 'One Size',
        sellingPrice: 700000,
        quantity: 1,
    },
    {
        _id: '63e4b1c9f5a10a0012aabc05',
        _idProduct: '63e4a1c9f5a10a0012aabc05',
        productImage: 'https://example.com/product5.jpg',
        productName: 'Áo Khoác Dù',
        productColor: 'Gray',
        productSize: 'L',
        sellingPrice: 450000,
        quantity: 2,
    },
];
