export const mockDataSupplier = [
    {
        id: '0',
        supplierName: 'Richard Martin',
        supplierMa: 'Kit Kat',
        contact_number: 7687764556,
        supplierEmail: 'richard@gmail.com',
        isTaking: ['Taking Return'],
        on_the_way: '12',
    },
    {
        id: '1',
        supplierName: 'Richard Martin',
        supplierMa: 'Kit Kat',
        contact_number: 7687764556,
        supplierEmail: 'richard@gmail.com',
        isTaking: ['Taking Return'],
        on_the_way: '12',
    },
    {
        id: '2',
        supplierName: 'Richard Martin',
        supplierMa: 'Kit Kat',
        contact_number: 7687764556,
        supplierEmail: 'richard@gmail.com',
        isTaking: ['Taking Return'],
        on_the_way: '12',
    },
    {
        id: '3',
        supplierName: 'Richard Martin',
        supplierMa: 'Kit Kat',
        contact_number: 7687764556,
        supplierEmail: 'richard@gmail.com',
        isTaking: ['Taking Return'],
        on_the_way: '12',
    },
    {
        id: '4',
        supplierName: 'Richard Martin',
        supplierMa: 'Kit Kat',
        contact_number: 7687764556,
        supplierEmail: 'richard@gmail.com',
        isTaking: ['Taking Return'],
        on_the_way: '12',
    },
    {
        id: '5',
        supplierName: 'Richard Martin',
        supplierMa: 'Kit Kat',
        contact_number: 7687764556,
        supplierEmail: 'richard@gmail.com',
        isTaking: ['Taking Return'],
        on_the_way: '12',
    },
    // {
    //     id: '6',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '7',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '8',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '9',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '10',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '11',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '12',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '13',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '14',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '15',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '0',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '1',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '2',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '3',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '4',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '5',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '6',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '7',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '8',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '9',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '10',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '11',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '12',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '13',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '14',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '51',
    //     supplierName: 'Richard Martin',
    //     supplierMa: 'Kit Kat',
    //     contact_number: 7687764556,
    //     supplierEmail: 'richard@gmail.com',
    //     isTaking: ['Taking Return'],
    //     on_the_way: '12',
    // },
];

export const mockDataInventory = [
    {
        id: '0',
        supplierMa_name: 'Richard Martin',
        buying_price: 7680,
        quantity: 7680,
        thresholdValue: 10000,
        expiryDate: 'Taking Return',
        availability: '12',
    },
    {
        id: '1',
        supplierMa_name: 'Richard Martin',
        buying_price: 7680,
        quantity: 7680,
        thresholdValue: 10000,
        expiryDate: 'Taking Return',
        availability: '12',
    },
    {
        id: '2',
        supplierMa_name: 'Richard Martin',
        buying_price: 7680,
        quantity: 7680,
        thresholdValue: 10000,
        expiryDate: 'Taking Return',
        availability: '12',
    },
    {
        id: '3',
        supplierMa_name: 'Richard Martin',
        buying_price: 7680,
        quantity: 7680,
        thresholdValue: 10000,
        expiryDate: 'Taking Return',
        availability: '12',
    },
    {
        id: '4',
        supplierMa_name: 'Richard Martin',
        buying_price: 7680,
        quantity: 7680,
        thresholdValue: 10000,
        expiryDate: 'Taking Return',
        availability: '12',
    },
    {
        id: '5',
        supplierMa_name: 'Richard Martin',
        buying_price: 7680,
        quantity: 7680,
        thresholdValue: 10000,
        expiryDate: 'Taking Return',
        availability: '12',
    },
    {
        id: '6',
        supplierMa_name: 'Richard Martin',
        buying_price: 7680,
        quantity: 7680,
        thresholdValue: 10000,
        expiryDate: 'Taking Return',
        availability: '12',
    },
];
