export const mockDataSupplier = [
    {
        id: '0',
        supplier_name: 'Richard Martin',
        product: 'Kit Kat',
        contact_number: 7687764556,
        email: 'richard@gmail.com',
        type: ['Taking Return'],
        on_the_way: '12',
    },
    {
        id: '1',
        supplier_name: 'Richard Martin',
        product: 'Kit Kat',
        contact_number: 7687764556,
        email: 'richard@gmail.com',
        type: ['Taking Return'],
        on_the_way: '12',
    },
    {
        id: '2',
        supplier_name: 'Richard Martin',
        product: 'Kit Kat',
        contact_number: 7687764556,
        email: 'richard@gmail.com',
        type: ['Taking Return'],
        on_the_way: '12',
    },
    {
        id: '3',
        supplier_name: 'Richard Martin',
        product: 'Kit Kat',
        contact_number: 7687764556,
        email: 'richard@gmail.com',
        type: ['Taking Return'],
        on_the_way: '12',
    },
    {
        id: '4',
        supplier_name: 'Richard Martin',
        product: 'Kit Kat',
        contact_number: 7687764556,
        email: 'richard@gmail.com',
        type: ['Taking Return'],
        on_the_way: '12',
    },
    {
        id: '5',
        supplier_name: 'Richard Martin',
        product: 'Kit Kat',
        contact_number: 7687764556,
        email: 'richard@gmail.com',
        type: ['Taking Return'],
        on_the_way: '12',
    },
    // {
    //     id: '6',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '7',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '8',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '9',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '10',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '11',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '12',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '13',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '14',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '15',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '0',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '1',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '2',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '3',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '4',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '5',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '6',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '7',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '8',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '9',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '10',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '11',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '12',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '13',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '14',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
    // {
    //     id: '51',
    //     supplier_name: 'Richard Martin',
    //     product: 'Kit Kat',
    //     contact_number: 7687764556,
    //     email: 'richard@gmail.com',
    //     type: ['Taking Return'],
    //     on_the_way: '12',
    // },
];

export const mockDataInventory = [
    {
        id: '0',
        product_name: 'Richard Martin',
        buying_price: 7680,
        quantity: 7680,
        thresholdValue: 10000,
        expiryDate: 'Taking Return',
        availability: '12',
    },
    {
        id: '1',
        product_name: 'Richard Martin',
        buying_price: 7680,
        quantity: 7680,
        thresholdValue: 10000,
        expiryDate: 'Taking Return',
        availability: '12',
    },
    {
        id: '2',
        product_name: 'Richard Martin',
        buying_price: 7680,
        quantity: 7680,
        thresholdValue: 10000,
        expiryDate: 'Taking Return',
        availability: '12',
    },
    {
        id: '3',
        product_name: 'Richard Martin',
        buying_price: 7680,
        quantity: 7680,
        thresholdValue: 10000,
        expiryDate: 'Taking Return',
        availability: '12',
    },
    {
        id: '4',
        product_name: 'Richard Martin',
        buying_price: 7680,
        quantity: 7680,
        thresholdValue: 10000,
        expiryDate: 'Taking Return',
        availability: '12',
    },
    {
        id: '5',
        product_name: 'Richard Martin',
        buying_price: 7680,
        quantity: 7680,
        thresholdValue: 10000,
        expiryDate: 'Taking Return',
        availability: '12',
    },
    {
        id: '6',
        product_name: 'Richard Martin',
        buying_price: 7680,
        quantity: 7680,
        thresholdValue: 10000,
        expiryDate: 'Taking Return',
        availability: '12',
    },
];
